import sys
import os

# Add way_agent to the Python path so its internal imports (like `agents.supervisor`) work
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../way_agent')))

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from langchain_core.messages import HumanMessage
from graph import app as graph_app

router = APIRouter(
    prefix="/agent",
    tags=["agent"]
)

class ChatRequest(BaseModel):
    message: str

class ChatResponse(BaseModel):
    response: str
    agent: str

@router.post("/chat", response_model=ChatResponse)
async def chat_with_agent(request: ChatRequest):
    try:
        # Initialize state
        state = {"messages": [HumanMessage(content=request.message)]}
        
        # Run graph
        result = graph_app.invoke(state)
        
        # Extract the last message generated by an agent
        final_messages = result.get("messages", [])
        if len(final_messages) > 1:
            # Assuming the last message is from an agent
            last_msg = final_messages[-1].content
        else:
            last_msg = "No response generated."
            
        return ChatResponse(
            response=last_msg,
            agent=result.get("next", "Unknown")
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
