import os
from fastapi import FastAPI
from pydantic import BaseModel
from langchain_core.messages import HumanMessage
from graph import app as graph_app

app = FastAPI(title="WAY Transit Multi-Agent API", version="1.0")

class ChatRequest(BaseModel):
    message: str

class ChatResponse(BaseModel):
    response: str
    agent: str

@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    # Initialize state
    state = {"messages": [HumanMessage(content=request.message)]}
    
    # Run graph
    result = graph_app.invoke(state)
    
    # Extract the last message generated by an agent
    final_messages = result.get("messages", [])
    if len(final_messages) > 1:
        # Assuming the last message is from an agent
        last_msg = final_messages[-1].content
    else:
        last_msg = "No response generated."
        
    return ChatResponse(
        response=last_msg,
        agent=result.get("next", "Unknown")
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
